name: esri_eventos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  flutter_bloc: ^9.1.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cards/
    - assets/images/inicio/
    - assets/images/invitados/
    - assets/images/onboarding/
    - assets/images/profile/
    - assets/images/experiencias/
    - assets/images/post_evento/


  flutter:
  fonts:
    - family: AvenirNextUltraLight
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-UltLt.ttf

    - family: AvenirNextThin
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Thin.ttf

    - family: AvenirNextLight
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Light.otf

    - family: AvenirNextRegular
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Regular.ttf

    - family: AvenirNextMedium
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Medium.ttf

    - family: AvenirNextDemi
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Demi.ttf

    - family: AvenirNextBold
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Bold.ttf

    - family: AvenirNextHeavy
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Heavy.ttf